"""sprint0 cleanup relationships status publishing fields

Revision ID: 7bb70c4aeb77
Revises: 003
Create Date: 2026-07-07 21:55:46.209487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb70c4aeb77'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('s3_bucket', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('s3_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('public_url', sa.String(length=1000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    op.execute("UPDATE source_documents SET document_type = 'article' WHERE document_type IS NULL")

    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'article'"),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('public_url')
        batch_op.drop_column('s3_key')
        batch_op.drop_column('s3_bucket')
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
